### ISSUE TITLE
invalid ELF header  when I use it on docker 

### ISSUE THREAD

**Issue by lagmanzaza** [kelektiv/node.bcrypt.js#578]
> FROM node:carbon

> RUN npm install nodemon -g
> WORKDIR /app
> COPY . /app
> RUN npm install
> 
> 
> EXPOSE 3030
> 
> #CMD [ "npm","start" ]
> CMD [ "npm" , "run" ,"dev" ]

**Comment by agathver** [comment]
This looks like you are copying the `node_modules` from your local, which is probably not Linux.

Add a `.dockerignore` excluding `node_modules`

Feel free to reopen, if issue persists.

**Comment by JulianeAlbuquerque** [comment]
Hello, I'm had the same problem :(

**Comment by Alek-S** [comment]
facing similar error, but with dockerignore for node_modules. I have tried various configs including doing npm rebuild and rm -rf of node modules, but not much progress

.dockerignore:
```
node_modules
.DS_Store
data
```

dockerfile:
```
FROM node:11.15.0

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app/package.json
RUN npm install

COPY . /app

EXPOSE 5000

CMD ["npm","run", "start:prod" ]
```

**Comment by artoodeeto** [comment]
I have the same error. 
I have node version `v12.13.1`
bcrypt version: `"3.0.7"`

Dockerfile:

```
FROM node:12.13.1
WORKDIR /server
COPY . .
RUN npm install
EXPOSE 8000
CMD ["npm", "run", "dev"]
```

docker-compose.yml
```
version: "3.3"
services:
  db:
    build: ./db
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    networks:
      - app_network
  server:
    depends_on:
      - "db" # this is important for sql connection. it has to wait for mysql to establish connection then run this bish
    build: .
    command: ["npm", "run", "dev"]
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /server # this name is from dockerfile workdir
    networks:
      - app_network

networks:
  app_network:
volumes:
  app_volume:
```

dockerignore file:

```
node_modules
.env
.vscode
```

did you resolve this issue? @JulianeAlbuquerque @lagmanzaza
