### ISSUE TITLE
bcrypt fails in GitHub Actions

### ISSUE THREAD

**Issue by nebbles** [kelektiv/node.bcrypt.js#813]
When running jest tests in a typescript project, the following error occurs:

```
Cannot find module '/home/runner/work/server/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node' from 'node_modules/bcrypt/bcrypt.js'

    Require stack:
      node_modules/bcrypt/bcrypt.js
      src/________
      src/________
      src/________
      src/________
      tests/________.spec.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
      at Object.<anonymous> (node_modules/bcrypt/bcrypt.js:6:16)

```

NodeJS version `12.18.0`

This error is not reproducible either locally or CircleCI. I was setting up GitHub Actions to migrate from CircleCI and got this error for the first time.

I tried removing and adding bcrypt as a dependency. This took me up to version `5.0.0` of bcrypt but still the issue persists - but only when run in a GH Actions Job.

The following is my workflow YAML that I now use. Note I have removed some env variables from this snippet.

**Note** - this snippet does run, but only because I added the `npm rebuild --update-binary bcrypt` as a workaround as explained in the comment. If I remove that step of the test job then the tests fail in the `yarn ci-test` step. 
```
name: Node CI

on: push

env:
  node_version: "12.18.0"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: Get path of Yarn's cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-v1-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-scripts

      # There is an issue with bcrypt when it is run in this job, so before
      # testing we need to rebuild the binaries that bcrypt depends on, as seen
      # in this thread: https://github.com/mapbox/node-pre-gyp/issues/477
      # However since we do not want to mess with the lockfile, we use the
      # following command:
      # https://github.com/yarnpkg/yarn/issues/5271#issuecomment-493259425
      - run: npm rebuild --update-binary bcrypt

      - run: yarn ci-test
```

For reference, the ci-test step runs: `JEST_DEFAULT_TIMEOUT=60000 jest --ci --runInBand --logHeapUsage`

I wonder if this is a known issue or if at all it can be explained? As noted, I did find that workaround but I wonder if there is a proper way to fix this. As mentioned earlier, I do not have this issue with CircleCI or locally (I can provide the circleci.yml if needed).

I hope I have provided enough information for at least a query into why this might be happening. Let me know if there is anything else I could provide and I will happily try and source it asap. Thanks
